remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: sonus
description: A Max/MSP package for sound experimentation and algorithmic composition
show_downloads: false
logo: icon.png
